### ISSUE TITLE
ve can setup  problem 

### ISSUE THREAD

**Issue by MS123uk** [kwindrem/VeCanSetup#14]
Ve can setup  problem   
![IMG_2022-12-23-20-25-37-051](https://user-images.githubusercontent.com/118858054/209404951-0b7c7037-9197-4d6a-a071-1f1c3e845e21.jpg)
can not get parts this

**Comment by kwindrem** [comment]
You will not get past that. As the message says, you need command line access and run VeCanSetup's setup script from there.
