### ISSUE TITLE
Two batteries via can shows on product ID 512

### ISSUE THREAD

**Issue by Micha854** [kwindrem/VeCanSetup#20]
Hello, Great Work first!

I connected two batteries to my Raspberry via CAN bus. Both get the product ID 512.

Only the memory last recognized is displayed in the device list!

the first batterie is connected via can-hat waveshare for raspberry
the second ist connected with canable adapter via usb

How can we solve this problem?

**Comment by kwindrem** [comment]
This is something Victron will need to address. If you are using a third party battery monitor, they would probably need to be involved also.
