### ISSUE TITLE
Misslabeled installation instruction with can hat

### ISSUE THREAD

**Issue by ansgar-santic** [kwindrem/VeCanSetup#26]
I might have found a instruction spelling mistake. When first installing a new CAN Hat, you need to add the CAN hat and define which one it is. After this the instruction says continue with (cr) but that is listed as invalid action. 
I found out that its supposed to be enter

Shitty Explanation, have a look at my attached Screenshot

![image](https://github.com/kwindrem/VeCanSetup/assets/84678928/112904ee-feca-4582-adc2-e9e62d1627bd)

**Comment by kwindrem** [comment]
I assumed most people would understand "(cr)" to be just return/enter with no text at the prompt. I'll think of a better way to express this.

**Comment by ansgar-santic** [comment]
dayum, well then im the representation of probably the dumb user :D Thanks anyways!

**Comment by kwindrem** [comment]
I've updated prompting to hopefully make things more clear:

Available actions:
  Add a USB interface (a <interface>)
  Delete existing interface (d <interface>)
  blank line if done with changes
