### ISSUE TITLE
Waveshare 16MHz support

### ISSUE THREAD

**Issue by ArjanGoossens** [kwindrem/VeCanSetup#27]
It seems there is another Waveshare variant (which i have) with a 16MHz crystal.

Can you add the 16MHz version as well?

Overlay config is the same as for the 12MHz, just a different frequency

Many thanks!

this config works for me:
#### begin CAN overlay
# Waveshare 1-channel CANbus Hat 16 MHz crystal
# instantiates as can0 ONLY !!!
# use udev rules to rename
[all]
dtparam=spi=on
dtoverlay=mcp2515-can0,oscillator=16000000,interrupt=25,spimaxfrequency=2000000
#### end CAN overlay

**Comment by kwindrem** [comment]
done
