### ISSUE TITLE
Waveshare 1-channel CANbus Hat 8 MHz errors

### ISSUE THREAD

**Issue by Thaelian** [kwindrem/VeCanSetup#29]
Using the Waveshare 1-channel CANbus Hat 8 MHz HAT (the RS485 CAN HAT to be more specific, https://www.waveshare.com/wiki/RS485_CAN_HAT) on VenusOS 3.11, I get a lot of errors when connecting to my Pylontech battery bank. 

Looking at the CAN Network on VenusOS, I see 26% errors and overuns on the RX side. This makes the data refresh for the bank very very slow due to all the retries.

This worked perfectly using the same hardware on VenusOS 2.73 and only became an issue when going to the new version of VenusOS running Python3.

It would be wonderful if you could perhaps fix this?

**Comment by kwindrem** [comment]
This is beyond what VeCanSetup can address. All VeCanSetup does is setup rules for the CANbus hat. Actual communication is handled by code in the stock Venus OS.
You might open a discussion in the modifications section of the Victron community forum.
